[database]
database = seismon
host = localhost
port = 5432
user = seismon
password = seismon
min_eq_magnitude = 4.5

[pdlcient]
directory = /var/lib/seismon/ProductClient/data/receiver_storage/origin 
